export const questionPool = [
  {
    id: 1,
    difficulty: "easy",
    text: "Yazılım dünyasında <b>Böcek</b> anlamına gelen ve hatayı ifade eden terim nedir?",
    options: ["Insect", "Bug", "Worm", "Spider"],
    correct: 1,
  },
  {
    id: 2,
    difficulty: "easy",
    text: "Web sitelerinin iskeletini oluşturan işaretleme dili hangisidir?",
    options: ["HTML", "C", "Python", "Java"],
    correct: 0,
  },
  {
    id: 3,
    difficulty: "easy",
    text: "Bilgisayarın <b>geçici hafızası</b> olarak bilinen ve elektrik gidince sıfırlanan donanım?",
    options: ["İşlemci", "Monitör", "RAM", "USB"],
    correct: 2,
  },
  {
    id: 4,
    difficulty: "easy",
    text: "Aşağıdaki kısayollardan hangisi evrensel olarak <b>'Geri Al' (Undo)</b> işlemini yapar?",
    options: ["Ctrl + C", "Ctrl + Z", "Ctrl + V", "Alt + F4"],
    correct: 1,
  },
  {
    id: 5,
    difficulty: "easy",
    text: "Yapay Zeka (AI) kısaltmasındaki <b>'I'</b> harfi neyi temsil eder?",
    options: ["Internet", "Information", "Intelligence", "Innovation"],
    correct: 2,
  },
  {
    id: 6,
    difficulty: "easy",
    text: "Bir görseli oluşturan en küçük görüntü birimine ne ad verilir?",
    options: ["Pixel", "Voxel", "Bit", "Byte"],
    correct: 0,
  },
  {
    id: 7,
    difficulty: "easy",
    text: "iPhone telefonların işletim sistemi nedir?",
    options: ["Android", "Windows Phone", "iOS", "MacOS"],
    correct: 2,
  },
  {
    id: 8,
    difficulty: "easy",
    text: "Sosyal medya devi <b>Facebook</b> adını ne olarak değiştirdi?",
    options: ["Verse", "Meta", "Social", "Connect"],
    correct: 1,
  },
  {
    id: 9,
    difficulty: "easy",
    text: "Aşağıda gördüğünüz dünyaca ünlü <b>'Yıldızlı Gece' (The Starry Night)</b> tablosu hangi ressama aittir?<br><br><img src='/van-gogh.png' class='w-full max-h-48 object-contain rounded-lg border border-gray-300'>",
    options: [
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Salvador Dali",
      "Vincent van Gogh",
    ],
    correct: 3,
  },
  {
    id: 10,
    difficulty: "easy",
    text: "Bu gizemli gülümsemeye sahip <b>'Mona Lisa'</b> tablosunun yaratıcısı kimdir?<br><br><img src='/mona-lisa.png' class='w-full max-h-48 object-contain rounded-lg border border-gray-300'>",
    options: ["Michelangelo", "Donatello", "Leonardo da Vinci", "Raphael"],
    correct: 2,
  },
  {
    id: 11,
    difficulty: "easy",
    text: "Dijital tasarımda renklerin karışımını ifade eden <b>RGB</b> kısaltması hangi renkleri temsil eder?",
    options: [
      "Red, Green, Blue",
      "Red, Gold, Black",
      "Royal, Green, Brown",
      "Rose, Grey, Blue",
    ],
    correct: 0,
  },
  {
    id: 12,
    difficulty: "easy",
    text: "Sanatta ve mimaride mükemmel uyumu ifade eden orana ne ad verilir?",
    options: ["Altın Oran", "Gümüş Oran", "Pi Sayısı", "Muhteşem Yüzyıl"],
    correct: 0,
  },
  {
    id: 13,
    difficulty: "easy",
    text: "Sinema tarihinde 'Star Wars' (Yıldız Savaşları) evrenini yaratan efsanevi yönetmen kimdir?",
    options: [
      "Steven Spielberg",
      "George Lucas",
      "Christopher Nolan",
      "Quentin Tarantino",
    ],
    correct: 1,
  },
  {
    id: 14,
    difficulty: "easy",
    text: "Doğadaki sarmallarda ve yazılım algoritmalarında sıkça kullanılan <b>Fibonacci</b> dizisinin sıradaki sayısı kaçtır?<br><br><code class='bg-gray-900 text-yellow-400 px-4 py-2 rounded text-xl tracking-widest'>1, 1, 2, 3, 5, 8, ?</code>",
    options: ["10", "11", "13", "21"],
    correct: 2,
  },
  {
    id: 15,
    difficulty: "medium",
    text: "Grafik tasarımda ve baskı işlerinde kullanılan (Camgöbeği, Eflatun, Sarı, Siyah) renk modelinin kısaltması nedir?",
    options: ["RGB", "CMYK", "HEX", "HSL"],
    correct: 1,
  },
  {
    id: 16,
    difficulty: "medium",
    text: "1997 yılında dünya satranç şampiyonu Garry Kasparov'u yenen IBM yapımı bilgisayarın adı nedir?",
    options: ["Deep Blue", "AlphaGo", "Watson", "HAL 9000"],
    correct: 0,
  },
  {
    id: 17,
    difficulty: "medium",
    text: "Python programlama dilinde özellikle <b>veri analizi</b> (Data Analysis) için kullanılan en popüler kütüphane hangisidir?",
    options: ["NumPy", "Django", "Pandas", "Flask"],
    correct: 2,
  },
  {
    id: 18,
    difficulty: "medium",
    text: "Zoom yapıldığında (yakınlaştırıldığında) kalite kaybı yaşamayan, matematiksel formüllerle oluşturulan görsel türüne ne denir?",
    options: ["Raster", "Pixel", "Bitmap", "Vektör"],
    correct: 3,
  },
  {
    id: 19,
    difficulty: "medium",
    text: "Siber güvenlikte, kullanıcıları sahte e-postalarla kandırıp şifrelerini çalmaya çalışan saldırı türüne ne ad verilir?",
    options: ["DDoS", "Phishing (Oltalama)", "Brute Force", "SQL Injection"],
    correct: 1,
  },
  {
    id: 20,
    difficulty: "medium",
    text: "Bir web sitesinin kullanıcı arayüzü tasarımı <b>UI</b> ise, kullanıcı deneyimi tasarımı nedir?",
    options: ["UX", "CX", "IX", "DX"],
    correct: 0,
  },
  {
    id: 21,
    difficulty: "medium",
    text: "Yazılımda 'Açık Kaynak' (Open Source) ne anlama gelir?",
    options: [
      "Ücretsiz yazılım demektir",
      "Kodları herkese açık ve değiştirilebilir demektir",
      "Sadece internet varken çalışır",
      "Güvenlik açığı olan yazılımdır",
    ],
    correct: 1,
  },
  {
    id: 22,
    difficulty: "medium",
    text: "YouTube'a yüklenen tarihteki <b>ilk videonun</b> konusu neydi?",
    options: [
      "Bir kedi videosu",
      "Kodlama dersi",
      "Hayvanat bahçesi gezisi",
      "Kaykay yapan adam",
    ],
    correct: 2,
  },
  {
    id: 23,
    difficulty: "medium",
    text: "Efsanevi <b>Nokia 3310</b> telefonuyla özdeşleşen o meşhur oyun hangisidir?",
    options: ["Tetris", "Snake (Yılan)", "Pac-Man", "Space Invaders"],
    correct: 1,
  },
  {
    id: 24,
    difficulty: "medium",
    text: "Elon Musk, popüler sosyal medya platformu <b>Twitter</b>'ın adını ve logosunu ne olarak değiştirdi?",
    options: ["Y", "Z", "X", "T"],
    correct: 2,
  },
  {
    id: 25,
    difficulty: "medium",
    text: "Dijital sanat eserlerinin orijinalliğini blokzincir üzerinde belgeleyen sertifikaya ne ad verilir?",
    options: ["JPEG", "PNG", "NFT", "BTC"],
    correct: 2,
  },
  {
    id: 26,
    difficulty: "medium",
    text: "Android işletim sisteminin versiyon isimleri (Android 9'a kadar) alfabetik sırayla ne isimleriydi?",
    options: [
      "Gezegen İsimleri",
      "Ünlü Bilim İnsanları",
      "Tatlı / Şeker İsimleri",
      "Hayvan İsimleri",
    ],
    correct: 2,
  },
  {
    id: 27,
    difficulty: "medium",
    text: "Bir hilesiz zar atıldığında gelen sayının <b>4'ten büyük</b> olma olasılığı kaçtır?",
    options: ["1/2", "1/3", "1/4", "1/6"],
    correct: 1,
  },
  {
    id: 28,
    difficulty: "medium",
    text: "Yazılımcıların çok sevdiği <b>2 üzeri 10</b> değeri kaçtır? (1 Kilobyte)",
    options: ["1000", "1024", "512", "2048"],
    correct: 1,
  },
  {
    id: 29,
    difficulty: "medium",
    text: "Bir ürün %20 indirimle 80 TL'ye satılıyorsa, ürünün indirimsiz fiyatı kaç TL'dir?",
    options: ["96 TL", "100 TL", "120 TL", "90 TL"],
    correct: 1,
  },
  {
    id: 30,
    difficulty: "medium",
    text: "Aşağıdaki sayı dizisinde soru işareti yerine ne gelmelidir?<br><code class='bg-gray-900 text-yellow-400 px-2 py-1 rounded tracking-widest'>2, 6, 12, 20, 30, ?</code>",
    options: ["40", "42", "36", "48"],
    correct: 1,
  },
  {
    id: 31,
    difficulty: "medium",
    text: "Tasarımcıların ve yazılımcıların, yer tutucu (taslak) metin olarak kullandığı Latince kökenli anlamsız metin hangisidir?",
    options: ["Carpe Diem", "Lorem Ipsum", "Veni Vidi Vokke", "Harry Potter"],
    correct: 1,
  },
  {
    id: 32,
    difficulty: "medium",
    text: "FedEx logosunda 'E' ve 'x' harfleri arasında gizlenmiş olan ve 'hız/ilerleme'yi simgeleyen şekil nedir?<br><br><img src='/fedex-logo.png' class='w-full max-h-32 object-contain rounded-lg bg-white p-2'>",
    options: ["Bir uçak", "Bir şimşek", "Bir ok işareti", "Bir gülen yüz"],
    correct: 2,
  },
  {
    id: 33,
    difficulty: "medium",
    text: "Yazılımcıların, kodda hata ararken cansız bir nesneyle (genelde oyuncak) konuşarak sorunu çözmeye çalıştığı yöntemin adı nedir?<br><br><img src='/rubber-duck.png' class='w-24 h-24 mx-auto object-contain rounded-full border-2 border-yellow-400'>",
    options: [
      "Teddy Bear Talk",
      "Rubber Duck Debugging",
      "Toy Story Method",
      "Plastic Code Fix",
    ],
    correct: 1,
  },
  {
    id: 34,
    difficulty: "medium",
    text: "Tipografide, harflerin uç kısımlarındaki küçük çıkıntılara (tırnaklara) ne ad verilir?<br><br><img src='/serif-vs-sans.png' class='w-full max-h-32 object-contain rounded-lg bg-white p-2'>",
    options: ["Sans-Serif", "Serif", "Bold", "Italic"],
    correct: 1,
  },
  {
    id: 35,
    difficulty: "medium",
    text: "Yazılım ve oyun dünyasında, geliştiricilerin koda veya oyuna gizlediği sürprizlere/mesajlara ne ad verilir?",
    options: [
      "Bug (Böcek)",
      "Easter Egg (Paskalya Yumurtası)",
      "Spam",
      "Glitch",
    ],
    correct: 1,
  },

  {
    id: 36,
    difficulty: "medium",
    text: "ChatGPT gibi modellerin temelini oluşturan mimarinin adı nedir?",
    options: ["RNN", "Transformer", "LSTM", "CNN"],
    correct: 1,
  },
  {
    id: 37,
    difficulty: "medium",
    text: "Hangi renk kodu 'Tam Siyah'ı temsil eder?",
    options: ["#FFFFFF", "#000000", "#111111", "#999999"],
    correct: 1,
  },
  {
    id: 38,
    difficulty: "medium",
    text: "Linux işletim sisteminin maskotu olan hayvan hangisidir?",
    options: ["Kedi", "Köpek", "Penguen", "Balina"],
    correct: 2,
  },
  {
    id: 39,
    difficulty: "medium",
    text: "Aşağıdaki kodun çıktısı ne olur?<br><code class='bg-gray-800 text-white px-2 py-1 rounded text-sm'>print(10 % 3)</code>",
    options: ["3", "1", "3.33", "10"],
    correct: 1,
  },
  {
    id: 40,
    difficulty: "medium",
    text: "Tasarımda 'Altın Oran' yaklaşık olarak kaçtır?",
    options: ["1.618", "3.142", "1.414", "2.718"],
    correct: 0,
  },
  {
    id: 41,
    difficulty: "hard",
    text: "HTTP protokolünde '418' hata kodunun anlamı nedir? (Bir 1 Nisan şakasıdır)",
    options: [
      "Server on fire",
      "I'm a teapot",
      "Coffee not found",
      "Payment required",
    ],
    correct: 1,
  },
  {
    id: 42,
    difficulty: "hard",
    text: "Yapay zekada 'Turing Testi' neyi ölçmeyi amaçlar?",
    options: [
      "İşlemci hızını",
      "Makinenin insansı zekasını",
      "Veri depolama kapasitesini",
      "Enerji verimliliğini",
    ],
    correct: 1,
  },
  {
    id: 43,
    difficulty: "hard",
    text: "Bir koşu yarışındasınız. <b>İkinciyi</b> geçerseniz kaçıncı olursunuz?",
    options: ["Birinci", "İkinci", "Üçüncü", "Sondancı"],
    correct: 1,
  },
  {
    id: 44,
    difficulty: "hard",
    text: "Yazılımda bir fonksiyonun <b>kendini çağırması</b> işlemine ne ad verilir?",
    options: [
      "Iteration (Döngü)",
      "Recursion (Özyineleme)",
      "Compilation (Derleme)",
      "Abstraction (Soyutlama)",
    ],
    correct: 1,
  },
  {
    id: 45,
    difficulty: "hard",
    text: "Aşağıdaki döngü kaç kez çalışır?<br><code class='bg-gray-900 text-white px-2 py-2 rounded text-sm text-left block'>for (int i = 0; i < 10; i += 2) {<br>  print(i);<br>}</code>",
    options: ["10 kez", "9 kez", "5 kez", "4 kez"],
    correct: 2,
  },
  {
    id: 46,
    difficulty: "hard",
    text: "Bir değişkenin sadece <b>'True'</b> veya <b>'False'</b> değeri alabildiği veri tipi hangisidir?",
    options: ["String", "Integer", "Boolean", "Float"],
    correct: 2,
  },
  {
    id: 47,
    difficulty: "hard",
    text: "Aşağıdaki mantıksal operatörlerden hangisi <b>'VE' (AND)</b> işlemini temsil eder?",
    options: ["||", "&&", "!", "=="],
    correct: 1,
  },
  {
    id: 48,
    difficulty: "hard",
    text: "Nesne Yönelimli Programlamada (OOP), bir sınıfın özelliklerini başka bir sınıfa aktarmasına ne denir?",
    options: [
      "Polymorphism (Çok Biçimlilik)",
      "Encapsulation (Kapsülleme)",
      "Inheritance (Miras Alma)",
      "Debugging (Hata Ayıklama)",
    ],
    correct: 2,
  },
  {
    id: 49,
    difficulty: "hard",
    text: "Dizilerde (Array) ilk elemanın indeksi (sıra numarası) genellikle kaçtır?",
    options: ["0", "1", "-1", "Tanımsız"],
    correct: 0,
  },
  {
    id: 50,
    difficulty: "hard",
    text: "Aşağıdaki kodun çıktısı ne olur?<br><code class='bg-gray-900 text-green-400 px-2 py-2 rounded text-sm'>x = 10<br>if (x > 5 and x < 8):<br>  print('A')<br>else:<br>  print('B')</code>",
    options: ["A", "B", "Hata verir", "Hiçbir şey yazmaz"],
    correct: 1,
  },
  {
    id: 51,
    difficulty: "hard",
    text: "Bilgisayarın anlayabildiği, sadece 0 ve 1'lerden oluşan en alt seviye dile ne denir?",
    options: ["Assembly", "Makine Dili (Machine Code)", "Python", "Java"],
    correct: 1,
  },
  {
    id: 52,
    difficulty: "hard",
    text: "Java/C# gibi dillerde 'String' indeksleri 0'dan başlar. Buna göre çıktı nedir?<br><br><code class='bg-gray-900 text-yellow-400 px-3 py-2 rounded text-lg block text-center'>kelime = \"YAZILIM\";<br>print(kelime[3]);</code>",
    options: ["Z", "I", "L", "M"],
    correct: 1,
  },
  {
    id: 53,
    difficulty: "hard",
    text: "Bir sayının <b>ÇİFT</b> olup olmadığını anlamak için boşluğa ne gelmelidir?<br><br><code class='bg-gray-900 text-green-400 px-3 py-2 rounded text-lg block text-center'>if (sayi % 2 == ___)</code>",
    options: ["1", "2", "0", "True"],
    correct: 2,
  },
  {
    id: 54,
    difficulty: "hard",
    text: "Aşağıdaki <b>While</b> döngüsü ekrana hangi sayıları yazar?<br><br><code class='bg-gray-900 text-white px-2 py-2 rounded text-sm block text-left'>x = 3;<br>while (x > 0) {<br>  print(x);<br>  x--;<br>}</code>",
    options: ["0 1 2 3", "3 2 1 0", "3 2 1", "Sonsuz Döngü"],
    correct: 2,
  },
  {
    id: 55,
    difficulty: "hard",
    text: "Dizi (Array) elemanlarına göre aşağıdaki toplama işleminin sonucu kaçtır?<br><br><code class='bg-gray-900 text-blue-300 px-2 py-2 rounded text-sm block text-left'>notlar = [10, 40, 50];<br>sonuc = notlar[0] + notlar[2];<br>print(sonuc);</code>",
    options: ["50", "60", "90", "Hata Verir"],
    correct: 1,
  },
  {
    id: 56,
    difficulty: "hard",
    text: "Kodlamada <b>'||'</b> (veya 'OR') operatörü kullanıldığında, koşulun <b>True</b> olması için ne gerekir?<br><br><code class='bg-gray-900 text-pink-400 px-2 py-1 rounded'>if (A || B)</code>",
    options: [
      "Sadece A doğru olmalı",
      "Sadece B doğru olmalı",
      "İkisi de doğru olmalı",
      "En az biri doğru olsa yeter",
    ],
    correct: 3,
  },
  {
    id: 57,
    difficulty: "hard",
    text: "Yapay zeka modellerinde, modelin eğitim verisini <b>ezberleyip</b> yeni verilerde başarısız olması durumuna ne denir?",
    options: [
      "Underfitting",
      "Overfitting (Aşırı Öğrenme)",
      "Backpropagation",
      "Normalization",
    ],
    correct: 1,
  },
  {
    id: 58,
    difficulty: "hard",
    text: "Python'da <b>List Slicing</b> (Dilimleme) kullanılarak yapılan bu işlemin çıktısı nedir?<br><br><code class='bg-gray-900 text-green-400 px-2 py-1 rounded text-lg'>print(\"YAZILIM\"[::-1])</code>",
    options: ["YAZILIM", "MILIZAY", "M", "Hata Verir"],
    correct: 1,
  },
  {
    id: 59,
    difficulty: "hard",
    text: "Derlenen (Compiled) dillerin aksine, kodu satır satır okuyup anında çalıştıran dillere (örn: Python, JS) ne ad verilir?",
    options: ["Interpreted", "Structured", "Functional", "Low-Level"],
    correct: 0,
  },
  {
    id: 60,
    difficulty: "hard",
    text: "İnternet tarayıcısına 'google.com' yazdığınızda, bu alan adını IP adresine (örn: 142.250.x.x) çeviren sistemin adı nedir?",
    options: [
      "DNS (Domain Name System)",
      "VPN (Virtual Private Network)",
      "HTTP (HyperText Transfer Protocol)",
      "DHCP (Dynamic Host Configuration)",
    ],
    correct: 0,
  },
  {
    id: 61,
    difficulty: "hard",
    text: "16'lık sayı sisteminde (Hexadecimal), <b>'F'</b> harfi onluk sistemde (Decimal) hangi sayıya karşılık gelir?",
    options: ["10", "12", "15", "16"],
    correct: 2,
  },
  {
    id: 62,
    difficulty: "hard",
    text: "Gordon Moore'un ortaya attığı 'Moore Yasası'na göre, mikroçip üzerindeki transistör sayısı yaklaşık her ne kadar sürede bir <b>ikiye katlanır</b>?",
    options: [
      "Her 6 ayda bir",
      "Her 10 yılda bir",
      "Her 18-24 ayda bir",
      "Her 5 yılda bir",
    ],
    correct: 2,
  },
  {
    id: 63,
    difficulty: "hard",
    text: "Siber güvenlikte, bir yazılım açığının geliştirici tarafından fark edilmeden önce saldırganlarca keşfedilip kullanılmasına ne denir?",
    options: ["Zero-Day Exploit", "Brute Force", "Trojan Horse", "Phishing"],
    correct: 0,
  },
  {
    id: 64,
    difficulty: "hard",
    text: "Web sitelerinin, kullanıcıyı hatırlamak ve oturumu açık tutmak için tarayıcıya kaydettiği küçük veri dosyalarına ne ad verilir?",
    options: [
      "Cache (Önbellek)",
      "Cookie (Çerez)",
      "History (Geçmiş)",
      "Token",
    ],
    correct: 1,
  },
  {
    id: 65,
    difficulty: "easy",
    text: "Bilgisayar faresini (mouse) hareket ettirdiğimizde ekranda beliren küçük ok işaretine ne ad verilir?",
    options: ["İmleç (Cursor)", "Buton", "Simge", "Piksel"],
    correct: 0,
  },
  {
    id: 66,
    difficulty: "easy",
    text: "İnternette bir web sitesine girmek için adres çubuğuna genellikle hangi kısaltma ile başlarız?",
    options: ["www", "abc", "com", "net"],
    correct: 0,
  },
  {
    id: 67,
    difficulty: "easy",
    text: "Klavyedeki en uzun tuş hangisidir?",
    options: ["Enter", "Shift", "Boşluk (Space)", "Backspace"],
    correct: 2,
  },
  {
    id: 68,
    difficulty: "easy",
    text: "Cep telefonlarında kullanılan, elma logolu marka hangisidir?",
    options: ["Samsung", "Apple", "Huawei", "Nokia"],
    correct: 1,
  },
  {
    id: 69,
    difficulty: "easy",
    text: "Fotoğraf paylaşım uygulaması Instagram'ın logosunda hangi nesneye benzer bir şekil vardır?",
    options: ["Kamera", "Telefon", "Televizyon", "Radyo"],
    correct: 0,
  },
  {
    id: 70,
    difficulty: "easy",
    text: "WhatsApp uygulamasında mesajın okunduğunu gösteren işaret nedir?",
    options: [
      "Tek Gri Tik",
      "Kırmızı Ünlem",
      "Mavi Çift Tik",
      "Sarı Gülen Yüz",
    ],
    correct: 2,
  },
  {
    id: 71,
    difficulty: "easy",
    text: "Dünyanın en zengin insanlarından biri olan ve Microsoft'un kurucusu olan ünlü isim kimdir?",
    options: ["Bill Gates", "Brad Pitt", "Cristiano Ronaldo", "Donald Trump"],
    correct: 0,
  },
  {
    id: 72,
    difficulty: "easy",
    text: "Bir metni kopyalamak için kullanılan klavye kısayolu hangisidir?",
    options: ["Ctrl + C", "Ctrl + V", "Ctrl + P", "Ctrl + S"],
    correct: 0,
  },
  {
    id: 73,
    difficulty: "easy",
    text: "Netflix ne tür bir hizmet sunan bir platformdur?",
    options: [
      "Müzik dinleme",
      "Film ve Dizi izleme",
      "Alışveriş yapma",
      "Mesajlaşma",
    ],
    correct: 1,
  },
];
